### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 3x0dv5**
Update the Install section to reflect the process of using version v1.0.0-preview4

### CODE REVIEW

**Comment by chanan** [comment]
Thanks!

**Comment by 3x0dv5** [comment]
No, thank you for this awesome work! I just came across this but looks pretty cool, taking it for a spin and see how it goes.

**Comment by chanan** [comment]
Let me know how it goes. I am sure there is a lot to improve.

**Comment by 3x0dv5** [comment]
Sure thing, if I find something I'll bring it up.

**Pull request merged**
